# Use postgres/example user/password credentials
services:
  db:
    image: postgres

    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      #Password here will be changed in production. This is only for testing purposes
      POSTGRES_PASSWORD: planningp
    ports:
      - 5432:5432

  adminer:
    image: adminer

    restart: always
    ports:
      - 8080:8080

  backend:
    restart: always
    build:
      context: .
      dockerfile: BackendDockerfile
    ports:
      - "3001:3001"

  nginx:
    image: nginx
    depends_on:
      - backend
    restart: always
    ports:
      - 80:80
    volumes:
      - ./src/infra/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./dist/.:/etc/nginx/html