# Use postgres/example user/password credentials

services:

    db:
        image: postgres
        restart: always
        # set shared memory limit when using docker compose
        shm_size: 128mb
        # or set shared memory limit when deploy via swarm stack
        #volumes:
        #  - type: tmpfs
        #    target: /dev/shm
        #    tmpfs:
        #      size: 134217728 # 128*2^20 bytes = 128Mb
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: planning-poker-020A #Password here will be changed in production. This is only for testing purposes
        ports:
            - 5432:5432

    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080